/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import org.junit.Test;

import app.controller.Controller;

import static org.junit.Assert.*;

public class AppTest {

    @Test 
    public void test1() {
        String[] args = {"1","1"};
        new Controller(args);
    }

    @Test 
    public void test2() {
        String[] args = {"1","96"};
        new Controller(args);
    }
}
